name: "\U0001F41B Bug Report"
description: 'Report a reproducible bug in the RN Google Sign In package'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this entire form.
  - type: checkboxes
    attributes:
      label: I have searched open and closed issues for this issue.
      options:
        - label: I have searched open and closed issues.
          required: true
  - type: checkboxes
    attributes:
      label: This is not a bug report for `DEVELOPER_ERROR`
      description: If you have an issue with `DEVELOPER_ERROR`, please read the [troubleshooting guide](https://react-native-google-signin.github.io/docs/troubleshooting#developer_error).
      options:
        - label: I have read the troubleshooting guide
          required: true
  - type: input
    attributes:
      label: Minimal reproducible example
      description: |
        A link to a GitHub repository containing a minimal reproducible example. This repository should include as little code as possible and not include extraneous dependencies.

        Please try to reproduce the bugs on the provided example app. Either provide a link to the repo that reproduces the bug or provide your version of the [`App.tsx` file](https://github.com/react-native-google-signin/google-signin/blob/master/example/src/App.tsx) that reproduces the issue and that we can easily use.

        If a reproducible example is not provided, your issue may be closed.
        [Learn more about creating a minimal reproducible example](https://stackoverflow.com/help/mcve).
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
        - web
    validations:
      required: true
  - type: textarea
    attributes:
      render: text
      label: Summary
      description: |
        Explain the steps we need to take to reproduce the issue. Include a video or screenshots if you think it may help.
        Clearly describe what the expected behavior is and what instead is actually happening. Be concise and precise in your description. Include the affected platforms (iOS, Android).
    validations:
      required: true
  - type: textarea
    attributes:
      render: text
      label: Your computer environment
      description: Run the `npx react-native info` command and paste its output in the field below.
    validations:
      required: true
