platform :ios, '9.0'
$node_modules_path = '../../node_modules'

require_relative "#{$node_modules_path}/@react-native-community/cli-platform-ios/native_modules"

target 'GoogleSigninSampleApp' do
  # Pods for GoogleSigninSampleApp
  pod 'FBLazyVector', :path => "#{$node_modules_path}/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{$node_modules_path}/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{$node_modules_path}/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{$node_modules_path}/react-native/Libraries/TypeSafety"
  pod 'React', :path => "#{$node_modules_path}/react-native/"
  pod 'React-Core', :path => "#{$node_modules_path}/react-native/"
  pod 'React-CoreModules', :path => "#{$node_modules_path}/react-native/React/CoreModules"
  pod 'React-Core/DevSupport', :path => "#{$node_modules_path}/react-native/"
  pod 'React-RCTActionSheet', :path => "#{$node_modules_path}/react-native/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{$node_modules_path}/react-native/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{$node_modules_path}/react-native/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{$node_modules_path}/react-native/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{$node_modules_path}/react-native/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{$node_modules_path}/react-native/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{$node_modules_path}/react-native/Libraries/Settings"
  pod 'React-RCTText', :path => "#{$node_modules_path}/react-native/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{$node_modules_path}/react-native/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{$node_modules_path}/react-native/"

  pod 'React-cxxreact', :path => "#{$node_modules_path}/react-native/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{$node_modules_path}/react-native/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{$node_modules_path}/react-native/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{$node_modules_path}/react-native/ReactCommon/jsinspector"
  pod 'ReactCommon/jscallinvoker', :path => "#{$node_modules_path}/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{$node_modules_path}/react-native/ReactCommon"
  pod 'Yoga', :path => "#{$node_modules_path}/react-native/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => "#{$node_modules_path}/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{$node_modules_path}/react-native/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{$node_modules_path}/react-native/third-party-podspecs/Folly.podspec"

  use_native_modules!("../..")
end
