/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * It was the copied to the repo to support old arch
 *
 * @generated by codegen project: GeneratePropsJavaInterface.js
 */

package com.reactnativegooglesignin;

import android.view.View;
import androidx.annotation.Nullable;

public interface RNGoogleSigninButtonManagerInterfaceCopy<T extends View> {
  void setDisabled(T view, boolean value);
  void setColor(T view, @Nullable String value);
  void setSize(T view, int value);
}
